### ISSUE TITLE
Using 'run' cmd in Github action returns 'unauthorized' code (missing permissions)

### ISSUE THREAD

**Issue by elyonz** [github/gh-models#35]
Just a simple run command will return an error in any Github Action workflow. Is there a  permission that we can set to enable it? (not that I could find..)

workflow.yml
```
name: Test GPT

jobs:
  test:
    name: GPT
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4

      - name: Install GH CLI (when using private runners)
        uses: dev-hanz-ops/install-gh-cli-action@v0.2.1
        with:
          gh-cli-version: 2.65.0

      - name: Install GH CLI models extension
        run: |
          gh extension install https://github.com/github/gh-models

      - name: Generate Text
        run: |
          test=$(gh models run gpt-4o "Hello?" | head -n 1)
          echo "Test GPT: $test"
```
Output:
```
Error: unauthorized
{"error":{"code":"unauthorized","message":"Resource not accessible by integration","details":"Resource not accessible by integration"}}
```
